Update 4/26/24

diff --git a/oc_functions b/oc_functions
--- a/oc_functions
+++ b/oc_functions
@@ -230,6 +230,16 @@ function oc_ingress_logs_any_router() {
   oc logs -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-${router}" | grep Running | head -1 | awk '{print $1}') --follow $@
 }
 
+function oc_ingress_logs_all_router() {
+  if [[ "$1" == "" ]]; then
+    router="default"
+  else
+    router="$1"
+  fi
+  shift 1
+  
+  oc logs -n openshift-ingress -l "ingresscontroller.operator.openshift.io/deployment-ingresscontroller=${router}" $@
+}
 
 function oc_ingress_logs_any_router_wait_appear() {
   if [[ "$1" == "" ]]; then
@@ -262,22 +272,27 @@ function oc_ingress_get_operator_image() {
 }
 
 function oc_ingress_enable_verbose_openshift_router() {
-  echo "Log in to quay.io"
-  podman login quay.io || return 1
-  image=$(oc_ingress_get_router_image)
-  podman pull --authfile /home/gspence/.secrets/pull-secret.txt $image || return 1
-  sha=$(echo "$image" |  awk -F":" '{print $2}')
-  tag_new="quay.io/gspence/openshift-router:${sha}"
-  podman build -t $tag_new  -<<EOF
-FROM $image
-ENTRYPOINT ["/usr/bin/openshift-router","--v=10"]
+  router=${1}
+  if [[ "$router" == "" ]]; then
+    router="default"
+  fi
+  oc -n openshift-ingress patch deploy/router-${router} --type=strategic --patch='{"spec":{"template":{"spec":{"containers":[{"name":"router","command":["/usr/bin/openshift-router","--v=10"]}]}}}}'
+}
+
+
+function oc_ingress_enable_verbose_openshift_router_image_local() {
+  level=10
+  if [[ "$3" != "" ]]; then
+    level=$3
+  fi
+  podman build -t $2  -<<EOF
+FROM $1
+ENTRYPOINT ["/usr/bin/openshift-router","--v=${level}"]
 EOF
   if [[ $? -ne 0 ]]; then
     echo "ERROR: Build failed"
     return 1
   fi
-  podman push $tag_new || return 1
-  oc_ingress_patch_router_image $tag_new || return 1
 }
 
 function oc_ingress_patch_router_image() {
@@ -296,6 +311,8 @@ function oc_ingress_patch_operator_image() {
     echo "ERROR: You need to provide an image"
     return 1
   fi
+  # For later use, if we NEED the CVO, but just don't want it to manage ingress...
+  #oc patch clusterversion version --type json -p '[{"op":"add","path":"/spec/overrides","value":[{"kind":"Deployment","group":"apps","name":"ingress-operator","namespace":"openshift-ingress-operator","unmanaged":true}]}]'
   oc scale --replicas 0 -n openshift-cluster-version deployments/cluster-version-operator
   oc -n openshift-ingress-operator patch deploy/ingress-operator --type=strategic --patch='{"spec":{"template":{"spec":{"containers":[{"name":"ingress-operator","image":"'${1}'"}]}}}}'
   oc -n openshift-ingress-operator patch deploy/ingress-operator --type=strategic --patch='{"spec":{"template":{"spec":{"containers":[{"name":"ingress-operator","imagePullPolicy":"Always"}]}}}}'
@@ -305,6 +322,14 @@ function oc_ingress_force_delete_terminating_router_pods() {
   for i in $(oc get pods -n openshift-ingress --no-headers | grep Terminating | awk '{print $1}'); do
     oc delete -n openshift-ingress pod $i --force
   done
+}
+
+function oc_ingress_cleanup_old_router_pods() {
+  hash=$(oc get deployment -n openshift-ingress router-default -o jsonpath={.spec.template.metadata.labels} | jq -r '.["ingresscontroller.operator.openshift.io/hash"]')
+  for i in $(oc get pods -n openshift-ingress -o json | jq -r '.items[] | select(.metadata.labels."ingresscontroller.operator.openshift.io/hash"  != "6d58594c8b") | .metadata.name' | grep "router-"); do
+    oc delete pod -n openshift-ingress $i --wait=false
+  done
+  oc_ingress_force_delete_terminating_router_pods
 }
 
 function oc_ingress_maxconn_auto() {
@@ -498,11 +523,22 @@ function oc_ingress_clusterbuild_operator(){
   if [[ "$1" != "" ]]; then 
     tag="$1"
   fi
+  fix_makefile_cgo
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: fix_makefile_cgo failed"
+    return 1
+  fi
   make
   if [[ $? -ne 0 ]]; then
     echo "ERROR: Make failed"
     return 1
   fi
+  revert_makefile_cgo
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: revert_makefile_cgo failed"
+    return 1
+  fi
+
   podman login quay.io
   img=$(REGISTRY_AUTH_FILE=/home/gspence/.secrets/pull-secret.txt oc adm release info --pullspecs | grep cluster-ingress-operator | awk '{print $2}')
   if [[ "$img" == "" ]]; then
@@ -526,6 +562,129 @@ function oc_ingress_clusterbuild_operator(){
   echo "Patched cluster-ingress-operator to $new_img"
 }
 
+function fix_makefile_cgo() {
+  if [[ ! -f Makefile ]]; then
+    echo "Error: ./Makefile doesn't exist"
+    return 1
+  fi
+  sed -i 's/CGO_ENABLED=1/CGO_ENABLED=0/g' Makefile
+}
+
+function revert_makefile_cgo() {
+  if [[ ! -f Makefile ]]; then
+    echo "Error: ./Makefile doesn't exist"
+    return 1
+  fi
+  sed -i 's/CGO_ENABLED=0/CGO_ENABLED=1/g' Makefile
+}
+
+function oc_ingress_clusterbuild_router(){
+  tag=$(date +%s)
+  if [[ "$1" != "" ]]; then 
+    tag="$1"
+  fi
+  fix_makefile_cgo
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: fix_makefile_cgo failed"
+    return 1
+  fi
+  make
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: Make failed"
+    return 1
+  fi
+  revert_makefile_cgo
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: revert_makefile_cgo failed"
+    return 1
+  fi
+
+  podman login quay.io
+  img="$2"
+  if [[ "$img" == "" ]]; then
+    img=$(REGISTRY_AUTH_FILE=/home/gspence/.secrets/pull-secret.txt oc adm release info --pullspecs | grep haproxy-router | awk '{print $2}')
+    if [[ "$img" == "" ]]; then
+      echo "ERROR: Couldn't get current cluster ingress operator image"
+      return 1
+    fi
+  fi
+  podman pull --authfile /home/${USER}/.secrets/pull-secret.txt $img
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: Failed to pull $img"
+    return 1
+  fi
+
+
+  container=$(podman create $img)
+  podman cp ~/src/github.com/openshift/router/openshift-router ${container}:/usr/bin/
+  podman cp ~/src/github.com/openshift/router/images/router/haproxy/conf/haproxy-config.template ${container}:/var/lib/haproxy/conf
+  new_img="quay.io/${USER}/router:${tag}"
+  podman commit $container $new_img
+  oc_ingress_enable_verbose_openshift_router_image_local $new_img $new_img
+  for i in {1..10}; do
+    podman push $new_img
+    if [[ $? -eq 0 ]]; then
+      break
+    fi
+    echo "Failed podman push $new_img...retrying"
+  done
+
+  oc_ingress_patch_router_image $new_img
+  echo "Patched router to $new_img"
+}
+
+
+function oc_ingress_clusterbuild_router_ontop_existing_image(){
+  tag=$(date +%s)
+  if [[ "$1" != "" ]]; then 
+    tag="$1"
+  fi
+ fix_makefile_cgo
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: fix_makefile_cgo failed"
+    return 1
+  fi
+  make
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: Make failed"
+    return 1
+  fi
+  revert_makefile_cgo
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: revert_makefile_cgo failed"
+    return 1
+  fi
+
+  podman login quay.io
+  img=$(oc_ingress_get_router_image)
+  if [[ "$img" == "" ]]; then
+    echo "ERROR: Couldn't get current cluster ingress operator image"
+    return 1
+  fi
+
+  podman pull --authfile /home/${USER}/.secrets/pull-secret.txt $img
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: Failed to pull $img"
+    return 1
+  fi
+
+  container=$(podman create $img)
+  podman cp ~/src/github.com/openshift/router/openshift-router ${container}:/usr/bin/
+  podman cp ~/src/github.com/openshift/router/images/router/haproxy/conf/haproxy-config.template ${container}:/var/lib/haproxy/conf
+  new_img="quay.io/${USER}/router:${tag}"
+  podman commit $container $new_img
+  for i in {1..10}; do
+    podman push $new_img
+    if [[ $? -eq 0 ]]; then
+      break
+    fi
+    echo "Failed podman push $new_img...retrying"
+  done
+
+  oc_ingress_patch_router_image $new_img
+  echo "Patched router to $new_img"
+}
+
 function oc_dns_patch_operator_image() {
   if [[ "$1" == "" ]]; then
     echo "ERROR: You need to provide an image"
@@ -544,9 +703,19 @@ function oc_dns_clusterbuild_operator(){
     echo "ERROR: Provide a tag name for your image"
     return 1
   fi
+  fix_makefile_cgo
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: fix_makefile_cgo failed"
+    return 1
+  fi
   make
   if [[ $? -ne 0 ]]; then
     echo "ERROR: Make failed"
+    return 1
+  fi
+  revert_makefile_cgo
+  if [[ $? -ne 0 ]]; then
+    echo "ERROR: revert_makefile_cgo failed"
     return 1
   fi
   podman login quay.io
@@ -580,9 +749,30 @@ function oc_dns_edit_operator_config {
   oc edit dnses.operator.openshift.io default $@
 }
 
+function oc_dns_patch_coredns_image() {
+  if [[ "$1" == "" ]]; then
+    echo "ERROR: You need to provide an image"
+    return 1
+  fi
+  oc scale --replicas 0 -n openshift-cluster-version deployments/cluster-version-operator
+  oc -n openshift-dns patch daemonset/dns-default --type=strategic --patch='{"spec":{"template":{"spec":{"containers":[{"name":"router","image":"'${1}'","imagePullPolicy":"Always"}]}}}}'
+  oc -n openshift-dns-operator patch deploy/dns-operator --type=strategic --patch='{"spec":{"template":{"spec":{"containers":[{"name":"dns-operator","env":[{"name":"IMAGE","value":"'${1}'"}]}]}}}}'
+}
+
+
 function oc_ingress_exec_router_all {
   for i in $(oc get pods -n openshift-ingress -o json | jq -r '.items[].metadata.name'); do
     echo $i;
     oc exec -n openshift-ingress $i $@
   done
+}
+
+function oc_apisever_patch_apiserver_image() {
+  if [[ "$1" == "" ]]; then
+    echo "ERROR: You need to provide an image"
+    return 1
+  fi
+  oc scale --replicas 0 -n openshift-cluster-version deployments/cluster-version-operator
+  oc -n openshift-apiserver patch deploy/apiserver --type=strategic --patch='{"spec":{"template":{"spec":{"containers":[{"name":"router","image":"'${1}'","imagePullPolicy":"Always"}]}}}}'
+  oc -n openshift-apiserver-operator patch deploy/openshift-apiserver-operator --type=strategic --patch='{"spec":{"template":{"spec":{"containers":[{"name":"openshift-apiserver-operator","env":[{"name":"IMAGE","value":"'${1}'"}]}]}}}}'
 }
